version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/opt/app
  client:
    build:
      dockerfile: halalfind-frontend/Dockerfile
      context: .
    ports:
      - 3000:3000
    environment:
      # TODO: Check if this actually makes a difference in vite hot reloads
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./halalfind-frontend/.:/app
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=local
      - POSTGRES_DB=halalfind
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
